/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.0.43.3
    Soft IP Version: 2.0.0
    2024 11 02 12:31:45
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module multiplier_acc_v2 (clk_i, clk_en_i, rst_i, data_a_i, data_b_i, result_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  rst_i;
    input  [17:0]  data_a_i;
    input  [17:0]  data_b_i;
    output  [36:0]  result_o;
endmodule