/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.0.43.3
    Soft IP Version: 2.0.0
    2025 02 17 15:09:11
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module multa (clk_i, clk_en_i, rst_i, data_a_i, data_b_i, result_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  rst_i;
    input  [7:0]  data_a_i;
    input  [7:0]  data_b_i;
    output  [16:0]  result_o;
endmodule